management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - env
          - refresh
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensinggroup # guarantee process-once semantics for a service
#        kafka:
#          binder:
#            zkNodes: 47.97.104.192
#            brokers: 47.97.104.192
#          consumer:
#            bootstrap-servers: 47.97.104.192:9092

  kafka:
    consumer:
      bootstrap-servers: 47.97.104.192:9092
  redis:
    host: www.jelex.tech
    port: 6379
    password: J4uJh%

kafka:
  bootstrap:
    servers: 47.97.104.192:9092
  group:
    licensingId: licensinggroup